QuickieLube.Razor/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace QuickieLube.Razor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

QuickieLube.Razor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuickieLube.Razor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

QuickieLube.Razor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuickieLube.Razor.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

QuickieLube.Razor/Pages/Vehicles/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuickieLube.Application.Vehicles;
using QuickieLube.Domain.Vehicles;

namespace QuickieLube.Razor.Pages.Vehicles
{
    public class EditModel : PageModel
    {
        private readonly IVehicleRepository _vehicleRepository;
        [BindProperty(SupportsGet = true)]
        public Vehicle Vehicle { get; set; }

        public EditModel(IVehicleRepository vehicleRepository)
        {
            _vehicleRepository = vehicleRepository;
        }

        public IActionResult OnGet(string id)
        {
            Vehicle = _vehicleRepository.GetVehicleById(id);

            if (Vehicle == null)
            {
                return RedirectToPage("/Error");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _vehicleRepository.EditVehicle(Vehicle);
                    return RedirectToPage("/Vehicles/VehicleSearch");
                }
                catch (Exception)
                {

                }
            }

            return Page();

        }
    }
}

QuickieLube.Razor/Pages/Vehicles/VehicleSearch.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuickieLube.Application.Vehicles;
using QuickieLube.Domain.Vehicles;

namespace QuickieLube.Razor.Pages.Vehicles
{
    public class VehicleSearchModel : PageModel
    {
        private readonly IVehicleRepository _vehicleRepository;
        [BindProperty(SupportsGet = true)]
        public IEnumerable<Vehicle> Vehicles { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchParams { get; set; }

        public VehicleSearchModel(IVehicleRepository vehicleRepository)
        {
            _vehicleRepository = vehicleRepository;
        }

        public IActionResult OnGet()
        {
            try
            {
                Vehicles = _vehicleRepository.SearchVehicle(SearchParams);
                return Page();
            }
            catch (Exception)
            {
                return RedirectToPage("/Error");
            }

        }

        public void OnPostClearSearchField()
        {
            SearchParams = "";
            OnGet();
        }

    }
}

QuickieLube.Razor/Pages/Index.cshtml
@page "/Index"
@model IndexModel
@{
    
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

QuickieLube.Razor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuickieLube.Razor</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link href="~/lib/bootstrap/dist/css/Common.css" rel="stylesheet" />

</head>
<body>
    <div class="wrapper mobile_hide">
        <div id="sidebar">
            <div class="sidebar-header">
                <h5>Quickie Lube</h5>
            </div>
        </div>
        <div id="sidebar_content">
            <div class="sidebar-header">
            </div>
        </div>
    </div>
    <div class="wrapper">
        <nav id="sidebar">
            <ul class="list-unstyled">
                <li>
                    <a href="#">Home</a>
                </li>
                <li class="active">
                    <a href="#">Vehicle Search</a>
                </li>
                <li>
                    <a href="#">Work Order</a>
                </li>
                <li>
                    <a href="#">Customer</a>
                </li>
                <li>
                    <a href="#">ESM</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Vehicle</a>
                </li>
                <li>
                    <a href="#">Fleet</a>
                </li>
                <li>
                    <a href="#">Warning</a>
                </li>
                <li>
                    <a href="#">Club</a>
                </li>
                <li>
                    <a href="#">To Bay</a>
                </li>
            </ul>
        </nav>
        <div class="container">
            <main role="main" class="pb-3 pt-5">
                @RenderBody()
            </main>

        </div>
    </div>


    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <partial name="_ValidationScriptsPartial" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

QuickieLube.Razor/Pages/Vehicles/Edit.cshtml
@page  "{id}"
@model QuickieLube.Razor.Pages.Vehicles.EditModel
@{
    ViewData["Title"] = "Vehicle Edit";
}
<h3>Edit</h3>
<form method="post" class="p-5">

    <input hidden asp-for="Vehicle.Id" />

    <div class="form-group row p-sm-2">
        <label class="col-sm-2 col-form-label" asp-for="Vehicle.Name"></label>
        <div class="col-sm-10">
            <input type="text" placeholder="Type Name" asp-for="Vehicle.Name" class="form-control" />
            <span asp-validation-for="Vehicle.Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row p-sm-2">
        <label class="col-sm-2 col-form-label" asp-for="Vehicle.Description"></label>
        <div class="col-sm-10">
            <input type="text" placeholder="Type Description" asp-for="Vehicle.Description" class="form-control" />
            <span asp-validation-for="Vehicle.Description" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row p-sm-2">
        <label class="col-sm-2 col-form-label" asp-for="Vehicle.VIN"></label>
        <div class="col-sm-10">
            <input type="text" placeholder="Type VIN" asp-for="Vehicle.VIN" class="form-control" />
            <span asp-validation-for="Vehicle.VIN" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row p-sm-2">
        <label class="col-sm-2 col-form-label" asp-for="Vehicle.Fleet"></label>
        <div class="col-sm-10">
            <input type="text" placeholder="Type Fleet" asp-for="Vehicle.Fleet" class="form-control" />
            <span asp-validation-for="Vehicle.Fleet" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row p-sm-2">
        <label class="col-sm-2 col-form-label" asp-for="Vehicle.LastService"></label>
        <div class="col-sm-10">
            <input type="text" placeholder="Type LastService" asp-for="Vehicle.LastService" asp-format="{0:yyyy-MM-dd}" class="form-control">
            <span asp-validation-for="Vehicle.LastService" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row p-sm-2">
        <div class="col-sm-12 divPadding">
            <button class="btn btn-primary col-12 m-2 col-lg-2">Update</button>
            <input class="d-block d-lg-none btn btn-primary col-12 col-lg-2 m-2" type="button" id="btnUndo" value="Undo" />
            <a asp-page="/Vehicles/VehicleSearch" class="btn btn-primary col-12 m-2 col-lg-2">Cancel</a>
        </div>
    </div>

</form>

@section Scripts{

    <script>
        // undo functionality for medium devices like tablet,mobile etc that have <768px screen size
        $('#btnUndo').click(function () {
            document.execCommand('undo', false, null);
        });
    </script>
}

QuickieLube.Razor/Pages/Vehicles/VehicleSearch.cshtml
@page "{handler?}"

@model QuickieLube.Razor.Pages.Vehicles.VehicleSearchModel
@{
    ViewData["Title"] = "Vehicle Search";
}

<div>
    <div class="d-flex justify-content-center"><h3>Vehicle Search</h3></div>
    <div class="">
        <div class="row d-flex justify-content-center align-items-center">
            <div class="col-md-6 p-xl-3">
                <div class="form">

                    <form method="get" id="submit">
                        <button type="submit" class="fa fa-search"></button>
                        <input type="text" asp-for="SearchParams" class="form-control form-input shadow p-3 mb-5 bg-body rounded" placeholder="Search by vehicle id, name, vin">
                    </form>

                    <form method="post" asp-page-handler="ClearSearchField">
                        <span class="left-pan">
                            <button type="submit" class="fa fa-times-circle"></button>
                        </span>
                    </form>

                </div>
            </div>
            <table class="table imagetable table-responsive p-xl-3 display" id="tblVehicleSearch" cellspacing="0">
                <thead>
                    <tr>
                        <th>Vehicle ID</th>
                        <th>Name</th>
                        <th>Vehicle</th>
                        <th>VIN</th>
                        <th>Fleet</th>
                        <th>Last Service</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var vehicle in Model.Vehicles)
                    {
                        <tr>
                            <td>@vehicle.Id</td>
                            <td>@vehicle.Name</td>
                            <td>@vehicle.Description</td>
                            <td>@vehicle.VIN</td>
                            <td>@vehicle.Fleet</td>
                            <td>@vehicle.LastService.Value.ToString("yyyy-MM-dd")</td>
                            <td><a id=@vehicle.Id class="btn btn-primary" asp-page="/Vehicles/Edit" asp-route-id="@vehicle.Id">Edit</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


@section Scripts{
    <script src="~/js/Vehicles/VehicleSearch.js"></script>
}